version: '3'

tasks:
  test:
    desc: "Run all tests"
    cmds:
      - uv run pytest tests/ -v

  test-stock:
    desc: "Run stock tests with output"
    cmds:
      - uv run pytest tests/test_stock.py -v -s

  test-player:
    desc: "Run player tests"
    cmds:
      - uv run pytest tests/test_player.py -v -s

  demo:
    desc: "Demo stock price changes"
    cmds:
      - uv run demo-stock
